### ISSUE TITLE
Crash during construction

### ISSUE THREAD

**Issue by LlubNek** [Elecs-Mods/E-Flux#1]
This mod crashes during construction.  I'm using E-Flux-1.8.9-1.0Alpha.106.jar and ElecCore-1.8.9-1.4.234.jar.

The important bit seems to be:

```
java.lang.NoSuchMethodError: elec332.core.client.model.RenderingRegistry.registerModelTextureLoader(Lelec332/core/client/model/model/IModelAndTextureLoader;)V
    at elec332.eflux.proxies.ClientProxy.<init>(ClientProxy.java:55)
```

Here's the full crash report:
http://pastebin.com/rstk66pp

And here's the game output:
http://pastebin.com/YTtNQt04

**Comment by Elec332** [comment]
Yes, this is a problem with the too-new ElecCore, Ill release a update today

**Comment by Elec332** [comment]
It will unfortunatly probably end up being tomorrow :(
