### ISSUE TITLE
Crash when mining copper

### ISSUE THREAD

**Issue by insuusvenerati** [Elecs-Mods/E-Flux#2]
Client crashes when mining copper with vanilla pickaxe. 
Issue occurs when only running eFlux and core mods.
Crash report: http://pastebin.com/JxAcinvf

**Comment by EndermanParty** [comment]
Have the same issue, I posted it on Elec-core's page, and I can confirm that this happens with every ore not just copper.

**Comment by insuusvenerati** [comment]
Update to the newest ElecCore. That fixed it for me.

**Comment by Elec332** [comment]
Yep, that indeed fixed it ;)

**Comment by insuusvenerati** [comment]
Out of curiosity I checked the commit for ElecCore. If i'm right it looks like you switched over to the 1.8 version of rendering?
