### ISSUE TITLE
Crash in 1.9 w/ E-Flux-1.9-1.0Beta.118

### ISSUE THREAD

**Issue by Schrubbls** [Elecs-Mods/E-Flux#3]
Hi elec, 
there seems to be a crash everytime i try to search your mod E-flux for 1.9 in jei
or selecting the manual.

http://pastebin.com/bMBaPaGP

Dunno if its my fault with the mods i have installed but i think i let you know 

sincerely
Schrubbls

**Comment by Elec332** [comment]
This is an JEI issue, I will make a pull request for JEI

**Comment by Elec332** [comment]
The latest version of JEI contains a fix: http://minecraft.curseforge.com/projects/just-enough-items-jei/files/2288200
