### ISSUE TITLE
1.9 Server Crash

### ISSUE THREAD

**Issue by modmuss50** [Elecs-Mods/E-Flux#4]
And another one,

https://gist.github.com/modmuss50/e9794f71a8e019f6d5a9

**Comment by kreezxil** [comment]
I am getting the same error.

Issue: e-flux-1.9-1.0beta.119.jar crashes dedicated forge server 1.9 build 1804 on startup while looking for a model

crash report:
https://gist.github.com/0c1f9fd631cb9df85bbe

fml server latest:
https://gist.github.com/e26cd9d33d9a0e47e954

**Comment by cauliflower69** [comment]
Another server crash http://pastebin.com/JTbkkpsH

**Comment by Gaelan** [comment]
@Elec332 Any news? I would love to have E-Flux on my server.
