### ISSUE TITLE
[Issue ?] MC 1.9 Construction crash

### ISSUE THREAD

**Issue by accessdenied0** [Elecs-Mods/E-Flux#5]
Hey @Elec332 ,

I got this strange construction crash (5/Post Initialization last steps): http://pastebin.com/kgJ9gJK3

I've been using the last Forge Version and didn't found any clue to fix this... 

access_denied

**Comment by Elec332** [comment]
Looks like it is not on my end, try contacting the NeoTech team (or BookShelfAPI team)
![areeglz](https://cloud.githubusercontent.com/assets/6115944/13956358/bbe37a34-f048-11e5-85d8-b3827480ccee.png)

**Comment by accessdenied0** [comment]
Sorry @Elec332,

wrong crash report. Here is the right one: http://pastebin.com/G6dMepG8

I linked an old one who was already solved... I messed up the URLs. Sorry.

**Comment by Elec332** [comment]
Fixed with the latest ElecCore release
