### ISSUE TITLE
1.8.9 Rendering crash when paired with JEI - version Alpha 113

### ISSUE THREAD

**Issue by MysticAura** [Elecs-Mods/E-Flux#6]
When looking through items in JEI, game crashes with the following issue.
[crash-2016-03-23_19.58.40-client.txt](https://github.com/Elecs-Mods/E-Flux/files/187062/crash-2016-03-23_19.58.40-client.txt)

**Comment by Elec332** [comment]
Hopefully fixed with the latest ElecCore release
