### ISSUE TITLE
 e-flux-1.9-1.0beta.124 crashes dedicated forge server 1.9 build 1811 on startup

### ISSUE THREAD

**Issue by kreezxil** [Elecs-Mods/E-Flux#7]
Issue: e-flux-1.9-1.0beta.124 crashes dedicated forge server 1.9 build 1811 on startup

crash report:
https://gist.github.com/7016abb369d20bff861e

fml server latest:
https://gist.github.com/5e968efddec9438ad1cd

**Comment by Elec332** [comment]
Duplicate of #4
